disabled_rules: 
 - trailing_whitespace
 - vertical_whitespace
 - superfluous_disable_command
 - nesting
 - unused_closure_parameter
 - identifier_name
 - redundant_string_enum_value
 - unused_optional_binding
 
excluded:
  - Pods
  - TestTaskCurrencies/Resources/R.generated.swift

line_length:
  warning: 140
  ignores_comments: true
  
type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1200

identifier_name:
  min_length: 2
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
